### ISSUE TITLE
I would like to take screenshot with extent reports 

### ISSUE THREAD

**Issue by rbhavsar** [naveenanimation20/PageObjectModel#1]
Hi @naveenanimation20 ,

With this code, I am able to get Extent report but not screenshot with this.
The code is available here https://github.com/naveenanimation20/ExtentReportCode/blob/master/src/test/java/FreeCRMTest.java
for the screenshot but How Can I use this PageObjectModel.
This seems like test case wise facility.

I am expecting Page Object Model + Extent Report + Screenshot.

 I am sure that I am missing something.Can you please guide me?

Thanks,
Ravi

**Comment by arkadiyala** [comment]
@rbhavsar  - Did you find solution? Please help me if you have solution

**Comment by arkadiyala** [comment]
Hi @naveenanimation20 , 

please help me on extended reports. Thanks for your help in advance.

**Comment by arkadiyala** [comment]
Hi @naveenanimation20,

I did not see screenshot when script is failed. Please help me how to get screenshot as well.

![image](https://user-images.githubusercontent.com/21693119/38833220-849782ba-418a-11e8-9f3c-f1593c47b71b.png)

**Comment by arkadiyala** [comment]
@rbhavsar 
@naveenanimation20 

Is there any way i can see failed screen shots under extent.html? ( I see them under 'screen shots' folder for now)

**Comment by arkadiyala** [comment]
@rbhavsar - Did you find solution? How to embed screenshots in report?

**Comment by guptapriyamca** [comment]
Hi @naveenanimation20 

Can we work on attaching Failed screenshots in Extent Report + WebEventListener  ?

I am trying to do like this, but it is not happening.

Another things is that i am using below code to add screenshots in already created folder whenever execution fails then OnException in WebEventListener is calling takeScreenshotAtEndOfTest from TestUtils  -

public static void takeScreenshotAtEndOfTest() throws IOException {
		
		String dtName=new SimpleDateFormat("yyyyMMddhhmmss").format(new Date());
		
		File scrFile = ((TakesScreenshot) driver).getScreenshotAs(OutputType.FILE);
		String currentDir = Screenshot_path + File.separator + dtName + ".png";
		
		
		FileUtils.copyFile(scrFile, new File(currentDir));
		
		
		}

Screenshot is getting generate in the folder but it is not happening always.Only 1st time Screenshot is getting generate.
I want to get screenshot always whenever I run any testng @Test.

Please Help!

**Comment by guptapriyamca** [comment]
> @rbhavsar
> @naveenanimation20
> 
> Is there any way i can see failed screen shots under extent.html? ( I see them under 'screen shots' folder for now)

Hi @rbhavsar,

Is Screenshots getting generate always whenever execution gets fail? 

Screenshot is getting generate  but it is not happening always.Only 1st time Screenshot is getting generate.
I want to get screenshot always whenever I run any testng @test.

Can you please help me on same ?

Thanks,
Priyanka
