### ISSUE TITLE
java.lang.RuntimeException: java.lang.NoClassDefFoundError: org/apache/xmlbeans/XmlObject

### ISSUE THREAD

**Issue by meetparag81** [naveenanimation20/PageObjectModel#2]
I have created my project by going through POM with datadriven approach videos posted on youtube, I   want to pass username and password in username and password input box by using xlsx file("Naukaridata.xlsx"), but I am getting following errors  
java.lang.RuntimeException: java.lang.NoClassDefFoundError: org/apache/xmlbeans/XmlObject is seen and after  going through logs I can see for this line in util class   book =  WorkbookFactory.create(file)  an error is  also seen in login test class in line  Object[][]data= TestUtil.getTestData(sheetname) 
I am attaching my project which includes all pom test base util classes  and xlsx file , so you can help me.
Waiting for your reply
Parag Borawake
[Myproject.zip](https://github.com/naveenanimation20/PageObjectModel/files/1809751/Myproject.zip)

**Comment by misranaman** [comment]
Include all the jars from this in your maven dependencies. This will resolve the issue

http://apache.claz.org/poi/release/bin/poi-bin-3.17-20170915.zip
