### ISSUE TITLE
When i tried to run LoginPageTest.java then TestNg is throwing some issue i have added the class files too but still facing this issue

### ISSUE THREAD

**Issue by sourabhQA** [naveenanimation20/PageObjectModel#5]
When i tried to run LoginPageTest.java then TestNg is throwing some issue i have added the class files too but still facing this issue
![facing this issue]

(https://user-images.githubusercontent.com/31312292/43565995-88e2142e-964a-11e8-8c53-c82807a41f0d.PNG)

**Comment by singhvikas72** [comment]
Hi,
I am getting an error "FAILED CONFIGURATION: @BeforeMethod setup" with null pointer exception" on my run of LoginPageTest.java  and after investing some time on R&D, I import FreeCRM MJ project to verify the same, but it working fine.Please guide me to fix the issue.

**Comment by seemamotwani** [comment]
Hi,
I am getting attached error for Test NG . could you please help

[Utils] [ERROR] [Error] org.testng.TestNGException: 
Cannot inject @Test annotated Method [login] with [class java.lang.String, class java.lang.String].
For more information on native dependency injection please refer to http://testng.org/doc/documentation-main.html#native-dependency-injection

**Comment by sourabhQA** [comment]
> Hi,
> I am getting an error "FAILED CONFIGURATION: @BeforeMethod setup" with null pointer exception" on my run of LoginPageTest.java and after investing some time on R&D, I import FreeCRM MJ project to verify the same, but it working fine.Please guide me to fix the issue.

Hey ,
Make sure you did'nt forget to set System.setProperty()
Please check if you have set the property and used the code line for initiating Weddriver
